# Generated by Django 5.0.6 on 2024-06-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_abstract_article_author_article_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
